# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Life in a Nutshell
email: superbacon314@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! It was originally created as an experiment in coding. If you have somehow stumbled upon it, I apologize. I wasn't sure how it would turn out, and was quite surprised when it did, in fact, turn out at all. Anyways, have a nice day!
baseurl: "blog" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  RAnderson21

# Build settings
markdown: kramdown
